// UI/front-end-react/src/App.js
import logo from './logo.svg';
import './App.css';
import { MapContainer, TileLayer, Marker } from "react-leaflet";
import '@bopen/leaflet-area-selection/dist/index.css';




function App() {

  return (<div>
      <form>
          <label>Enter an address:
              <input type="text" />
          </label>
      </form>
      <MapContainer
          className="markercluster-map"
          center={[51.0, 19.0]}
          zoom={4}
          maxZoom={18}
      >
        <TileLayer
            url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
            attribution='&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
        />

      </MapContainer>
      </div>
  );
}

export default App;

// UI/front-end/src/app/app.component.ts
import { Component, AfterViewInit} from '@angular/core';
import * as L from 'leaflet';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements AfterViewInit {
  title = 'front-end';
  // @ts-ignore
  private map;

  private initMap(): void {
    this.map = L.map('map', {
      center: [39.8282, -98.5795],
      zoom: 3
    });

    const tiles = L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
      maxZoom: 18,
      minZoom: 3,
      attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
    });

    tiles.addTo(this.map);

  }




    constructor() { }

    ngAfterViewInit(): void {
      this.initMap();
    }
}


<button mat-button>Move Servo 1</button>
<div class="map-container">
  <div class="map-frame">
    <div id="map"></div>
  </div>
</div>
<router-outlet></router-outlet>
